### ISSUE TITLE
I can't find 'ClangLto' in 'clang.py'

### ISSUE THREAD

**Issue by manggoguy** [vusec/instrumentation-infra#2]
Running setup.py of deltapointer, there is code 
"setup.add_instance(infra.instances.ClangLTO(DeltaTags.llvm))"
and the error occurs. The error messages are below

mok@mint:deltapointers$ ./setup.py run --build deltatags-test clang-lto deltatags
Traceback (most recent call last):
  File "./setup.py", line 15, in <module>
    setup.add_instance(infra.instances.ClangLTO(DeltaTags.llvm))
AttributeError: module 'infra.instances' has no attribute 'ClangLTO'

I can't find "ClangLto" in this project.
How can i do?

**Comment by taddeus** [comment]
I think you cloned the infra on the master branch, which is incompatible with the older version used by Delta Pointers (DP uses [this](https://github.com/vusec/instrumentation-infra/blob/e18044719ed70c7800e4452cdd7dc6bd1aa2c439/infra/instances/clang.py) version of the file). Try checkout out commit e180447 in the infra/ directory, or removing the infra/ directory and cloning it as a submodule with `git submodule update --init`.

**Comment by manggoguy** [comment]
Thanks, I resolved it.
